WebApp/scheduler/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^timetable/', include('timetable.urls')),
    url(r'^', include('timetable.urls'))
]

WebApp/timetable/urls.py
from django.conf.urls import url
from . import views

app_name = 'timetable'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^userlogin$', views.login_user, name='userlogin'),
	url(r'^userlogout$', views.logout_user, name='userlogout'),
	url(r'^password/$', views.change_password, name='password')
]

WebApp/timetable/models.py
from django.contrib.auth.models import Permission, User
from django.db import models

class Course(models.Model):
	course_id = models.CharField(max_length=10)
	slot = models.CharField(max_length=10)
	rooms = models.CharField(max_length=50)

	def __str__(self):
		return self.course_id

class Student(models.Model):
	roll_no = models.CharField(max_length=10)
	courses = models.ManyToManyField(Course)

	def __str__(self): 
		return self.roll_no

class Professor(models.Model):
	Prof_id = models.CharField(max_length=10)
	courses = models.ManyToManyField(Course)

	def __str__(self): 
		return self.Prof_id

WebApp/timetable/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Student, Professor, Course
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm

def index(request):
	#return render(request, 'timetable/index.html')
	return render(request, 'timetable/login.html')

def login_user(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			login(request, user)
			X=Student.objects.filter(roll_no=username)
			if X:
				linked_courses = [l for l in Student.objects.filter(roll_no=username)[0].courses.all()]
				return render(request, 'timetable/display.html', {'context': linked_courses})
			else:
				linked_courses = [l for l in Professor.objects.filter(Prof_id=username)[0].courses.all()]
				return render(request, 'timetable/displayp.html', {'context': linked_courses})
		else:
			return render(request, 'timetable/login.html', {'error_message': 'Invalid login'})

		#Student.objects.all().delete()
		#Professor.objects.all().delete()
		#Course.objects.all().delete()
		# csvfile = request.FILES['file1']
		# file_data = csvfile.read().decode("utf-8")
		# f1 = file_data.split("\n")
		# for line in f1:
		# 	cols=line.split(",")
		# 	temp=Course(course_id=cols[0],slot=cols[1],rooms=cols[2])
		# 	temp.save()

		# csvfile = request.FILES['file2']
		# file_data = csvfile.read().decode("utf-8")
		# f2 = file_data.split("\n")

		# for line in f2:
		# 	line_without_newline=line.rstrip()
		# 	cols=line_without_newline.split(",")
		# 	temp=Student(roll_no=cols[0])
		# 	temp.save()
		# 	for course in cols[1:]:
		# 		x=Course.objects.filter(course_id=course)
		# 		if x:
		# 			temp.courses.add(x[0])

		# csvfile = request.FILES['file3']
		# file_data = csvfile.read().decode("utf-8")
		# f3 = file_data.split("\n")

		# for line in f3:
		# 	line_without_newline=line.rstrip()
		# 	cols=line_without_newline.split(",")
		# 	temp=Professor(Prof_id=cols[0])
		# 	temp.save()
		# 	for course in cols[1:]:
		# 		x=Course.objects.filter(course_id=course)
		# 		if x:
		# 			temp.courses.add(x[0])

		# x = Student.objects.all()
		# for y in x:
		# 	s = y.roll_no
		# 	e = s + '@iitb.ac.in'
		# 	p = s + 'pass'
		# 	check = User.objects.filter(username=s)
		# 	if not check:
		# 		user = User.objects.create_user(username=s,email=e,password=p)
		# 		user.save()
		# x = Professor.objects.all()
		# for y in x:
		# 	s = y.Prof_id
		# 	e = s + '@iitb.ac.in'
		# 	p = s + 'pass'
		# 	check = User.objects.filter(username=s)
		# 	if not check:
		# 		user = User.objects.create_user(username=s,email=e,password=p)
		# 		user.save()

	return render(request, 'timetable/login.html')

def logout_user(request):
	logout(request)
	return render(request, 'timetable/login.html')

def change_password(request):
	if request.method == 'POST':
		form = PasswordChangeForm(request.user, request.POST)
		if form.is_valid():
			user = form.save()
			update_session_auth_hash(request, user)  # Important!
			# messages.success(request, 'Your password was successfully updated!')
			return redirect('/timetable/password/')
		# else:
		# 	messages.error(request, 'Please correct the error below.')
	else:
		form = PasswordChangeForm(request.user)
	return render(request, 'timetable/change_password.html', {
		'form': form
	})

WebApp/timetable/templates/timetable/change_password.html
<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save changes</button>
</form>
<!-- {% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %} -->

WebApp/timetable/templates/timetable/display.html
<html>
<head>
	<title>My Homepage</title>
  <meta charset="utf-8" />
  <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
  <style>
  body {
  	font-family: 'Roboto', sans-serif;
  	font-weight: 300;
  }
  .jumbotron {
  	background-size: cover;
  	background-color: rgb(106,175,202);
  	height: 200px;
  }
  h1 {
  	text-align: center;
  	color: rgb(255,255,255);
  }
  </style>
</head>

<body>
<section id="home" class="jumbotron" align="left">
  <div class="container">
  	<h1>Your Timetable</h1>
  </div>
</section><br><br>

<div class="container">
<table class="table table-hover">
	<thead>
	<tr>
		<th> Course_ID </th>
		<th> Slot </th>
		<th> Room </th>
	</tr>
	</thead>
	<tbody>
	{% for c in context %}
	<tr>
		<td> {{ c.course_id }} </td>
		<td> {{ c.slot }} </td>
		<td> {{ c.rooms }} </td>
	</tr>
	{% endfor %}
	</tbody>
</table>
</div>
<br>
<div class="container" align="right">
<a href="{% url 'timetable:password' %}">Change Password</a><br>
<a href="{% url 'timetable:userlogout' %}">LOGOUT</a>
</body>
</html>

WebApp/timetable/templates/timetable/displayp.html
<html>
<head>
  <title>My Homepage</title>
  <meta charset="utf-8" />
  <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
  <style>
  body {
  	font-family: 'Roboto', sans-serif;
  	font-weight: 300;
  }
  .jumbotron {
  	background-size: cover;
  	background-color: rgb(106,175,202);
  	height: 200px;
  }
  h1 {
  	text-align: center;
  	color: rgb(255,255,255);
  }
  </style>
</head>

<body>
<section id="home" class="jumbotron" align="left">
  <div class="container">
  	<h1>Your Timetable</h1>
  </div>
</section><br><br>

<div class="container">
<table class="table table-hover">
	<thead>
	<tr>
		<th> Course_ID </th>
		<th> Slot </th>
		<th> Room </th>
	</tr>
	</thead>
	<tbody>
	{% for c in context %}
	<tr>
		<td> {{ c.course_id }} </td>
		<td> {{ c.slot }} </td>
		<td> {{ c.rooms }} </td>
	</tr>
	{% endfor %}
	</tbody>
</table>
</div>
<br>
<div class="container" align="right">
<a href="{% url 'timetable:password' %}">Change Password</a><br>
<a href="{% url 'timetable:userlogout' %}">LOGOUT</a>
</body>
</html>

WebApp/timetable/templates/timetable/index.html
<form method="POST" action="/timetable/userlogin" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="file1" title='Please upload file in csv format only'>
    <input type="file" name="file2" title='Please upload file in csv format only'>
    <input type="file" name="file3" title='Please upload file in csv format only'>
    <button type="submit">Upload</button>
    </form>

WebApp/timetable/templates/timetable/login.html
<html>
<head>
    <title>Login Page</title>
  <meta charset="utf-8" />
  <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
  <style>
  body {
    font-family: 'Roboto', sans-serif;
    font-weight: 300;
  }
  .jumbotron {
    background-size: cover;
    background-color: rgb(106,175,202);
    height: 200px;
  }
  h1 {
    text-align: center;
    color: rgb(255,255,255);
  }
  </style>
</head>

<body>
<section id="home" class="jumbotron" align="left">
  <div class="container">
    <h1>Login</h1>
  </div>
</section><br><br>

{% block title %}{% endblock %}

{% block body %}
<div class="container">

    <div class="row">
        <div class="col-sm-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'timetable:userlogin'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-4">
                                <input id="id_username" maxlength="60" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-4">
                                <input id="id_password" maxlength="60" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
</body>

{% endblock %}